name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  build:
    needs: lint
    uses: ./.github/workflows/build.yml
    secrets:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DIRECT_URL: ${{ secrets.DIRECT_URL }}
      API_PORT: ${{ secrets.API_PORT }}
      NEXT_PUBLIC_API_BASE_URL: ${{ secrets.NEXT_PUBLIC_API_BASE_URL }}

  test:
    needs: build
    uses: ./.github/workflows/test.yml
    secrets:
      API_PORT: ${{ secrets.API_PORT }}
      TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
      TEST_DIRECT_URL: ${{ secrets.TEST_DIRECT_URL }}

  cypress:
    needs: build
    uses: ./.github/workflows/cypress.yml
    secrets:
      API_PORT: ${{ secrets.API_PORT }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DIRECT_URL: ${{ secrets.DIRECT_URL }}
      NEXT_PUBLIC_API_BASE_URL: ${{ secrets.NEXT_PUBLIC_API_BASE_URL }}
