name: Test

on:
  workflow_call:
    secrets:
      API_PORT:
        required: true
      TEST_DATABASE_URL:
        required: true
      TEST_DIRECT_URL:
        required: true
      TEST_JWT_SECRET:
        required: true
      TEST_JWT_REFRESH_SECRET:
        required: true

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build schemas package
        run: pnpm --filter @workspace/schemas build

      - name: Configure API environment for testing
        run: |
          echo "PORT=${{ secrets.API_PORT }}" > apps/api/.env.test
          echo "DATABASE_URL=${{ secrets.TEST_DATABASE_URL }}" >> apps/api/.env.test
          echo "DIRECT_URL=${{ secrets.TEST_DIRECT_URL }}" >> apps/api/.env.test
          echo "JWT_SECRET=${{ secrets.TEST_JWT_SECRET }}" >> apps/api/.env.test
          echo "JWT_REFRESH_SECRET=${{ secrets.TEST_JWT_REFRESH_SECRET }}" >> apps/api/.env.test
          echo "NODE_ENV=test" >> apps/api/.env.test

      - name: Generate Prisma Client
        run: pnpm turbo db:generate
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres

      - name: Build exceptions packages
        run: pnpm turbo run build --filter=@workspace/exceptions

      - name: Run Tests with Turborepo
        run: pnpm turbo run test
